### ISSUE TITLE
Download mirrors

### ISSUE THREAD

**Issue by wlcosta** [ydk122024/AIDE#3]
Hi,

Would it be possible to provide download mirrors? It is very difficult to download from pan.baidu without being in China.

Thanks!

**Comment by ydk122024** [comment]
Hi, we provide a Dropbox link for better access for researchers outside of China. 
The link is: https://www.dropbox.com/scl/fo/fib67gt6x9n4lzv79apuv/h?rlkey=4rbqg5mn1wyjfyoolk4vba3zx&dl=0.
